### ISSUE TITLE
No rendering example for me

### ISSUE THREAD

**Issue by andrew-oko-odion** [cbothner/react-activestorage-provider#38]
```
File is not defined
ReferenceError: File is not defined
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:6583)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:1499)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:4595)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:3422)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:3220)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at Object.<anonymous> (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:2357)
    at e (/home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:169)
    at /home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:527
    at /home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:536
    at /home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:31
    at /home/niceguy/workspace/javascript/next-custom/node_modules/react-activestorage-provider/dist/index.js:1122:36
```

Nextjs@latest

**Comment by AdnanTheExcellent** [comment]
I get the same error when trying to server side render.
